name: github pages

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev
          token: ${{ secrets.ACCESS_TOKEN }}
          ssh-key: ${{ secrets.SSH_PRIVATE }}
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.80.0'
          extended: true

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Composite package.json
        run: hugo -s exampleSite --themesDir=../.. mod npm pack

      - name: Setup Dependency
        run: npm install --prefix exampleSite

      - name: Setup public
        run: git worktree add -B gh-pages ./exampleSite/public origin/gh-pages

      - name: Clean public
        run: rm -rf ./exampleSite/public/*

      - name: Build
        run: hugo -s exampleSite --themesDir=../.. --minify --environment production -b https://kaiiiz.github.io/hugo-theme-monochrome

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          deploy_key: ${{ secrets.SSH_PRIVATE }}
          publish_dir: ./exampleSite/public
          publish_branch: gh-pages
